name: Render webp of applets and deploy to GitHub Pages

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  render-webp:
    runs-on: ubuntu-latest

    steps:
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Initialize submodule
        run: |
          git submodule init
          git submodule update --remote

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: (Re-)render applets
        run: npm run render -- --skip-db

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
